require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '16.0'
install! 'cocoapods', :deterministic_uuids => false

# BẮT BUỘC PHẢI CÓ DÒNG NÀY ĐỂ COCOAPODS TÌM ĐƯỢC PROJECT
project 'MeoPhim.xcodeproj'

target 'MeoPhim' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # is an initialization script used for apps
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MeoPhimTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # GIỮ NGUYÊN HÀM MẶC ĐỊNH CỦA REACT NATIVE
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # 1. Ép tất cả các Pods về iOS 16.0 và fix lỗi leveldb
    installer.pods_project.targets.each do |target|
      # Fix lỗi leveldb-library
      if target.name == 'leveldb-library'
        target.build_configurations.each do |config|
          config.build_settings['SKIP_INSTALL'] = 'YES'
        end
      end

      # Fix lỗi Resource Bundle
      if target.respond_to?(:resource_bundle_targets)
        target.resource_bundle_targets.each do |res_target|
          res_target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          end
        end
      end

      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      end
    end

    # 2. HACK TARGET CHÍNH (MeoPhim) ĐỂ SỬA LỖI ARM64 VÀ SWIFT
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.targets.each do |target|
        if target.name == 'MeoPhim'
          target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
            
            config.build_settings['LIBRARY_SEARCH_PATHS'] ||= ['$(inherited)']
            config.build_settings['LIBRARY_SEARCH_PATHS'] << '"$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)"'
            config.build_settings['LIBRARY_SEARCH_PATHS'] << '"$(SDKROOT)/usr/lib/swift"'
            
            config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)']
            config.build_settings['OTHER_LDFLAGS'] << '-ObjC' << '-lc++'
            config.build_settings['OTHER_LDFLAGS'] << '-framework' << 'CoreAudio'
            config.build_settings['OTHER_LDFLAGS'] << '-framework' << 'AudioToolbox'
            config.build_settings['OTHER_LDFLAGS'] << '-framework' << 'AVFoundation'
            
            config.build_settings['DEAD_CODE_STRIPPING'] = 'NO'
            config.build_settings['STRIP_INSTALLED_PRODUCT'] = 'NO'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
          end
        end
      end
      aggregate_target.user_project.save
    end
  end
end
