require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '16.0'
prepare_react_native_project!

target 'MeoPhim' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Enable hermes only if needed
    :hermes_enabled => true
  )

  target 'MeoPhimTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # Default React Native post install
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Fix duplicate symbol arm64 (GCDAsyncSocket) and configure Swift/Linking
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-tcp-socket'
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'GCDAsyncSocket=MeoGCDAsyncSocket']
        end
      end

      target.build_configurations.each do |config|
        # Sửa lỗi CoreAudioTypes và Symbols
        config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)', '-lc++', '-lsqlite3', '-lz', '-framework CoreAudio', '-framework AudioToolbox', '-framework AVFoundation', '-Wl,-weak_framework,CoreAudioTypes']
        
        # Thêm LIBRARY_SEARCH_PATHS để tìm đúng Swift runtime
        config.build_settings['LIBRARY_SEARCH_PATHS'] ||= ['$(inherited)', '"$(SDKROOT)/usr/lib/swift"', '"$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)"']
        
        # Đảm bảo build đúng cho máy thật (iPhone)
        config.build_settings['SDKROOT'] = 'iphoneos'
        config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
      end
    end
  end
end
