# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
project 'MeoPhim.xcodeproj'
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MeoPhim' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MeoPhimTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.targets.each do |target|
        if target.name == 'MeoPhim'
          target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
            config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
            
            # Quan trọng nhất: Ép link mọi symbols từ Objective-C
            config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)']
            config.build_settings['OTHER_LDFLAGS'] << '-ObjC' << '-lc++' << '-lc++abi'
            config.build_settings['OTHER_LDFLAGS'] << '-framework' << 'CoreAudio' << '-framework' << 'AudioToolbox' << '-framework' << 'AVFoundation'
            
            # Đảm bảo đường dẫn Pods được ưu tiên
            config.build_settings['LIBRARY_SEARCH_PATHS'] ||= ['$(inherited)']
            config.build_settings['LIBRARY_SEARCH_PATHS'] << '"$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)"'
            config.build_settings['LIBRARY_SEARCH_PATHS'] << '"$(SDKROOT)/usr/lib/swift"'
            config.build_settings['LIBRARY_SEARCH_PATHS'] << '"$(SRCROOT)/Pods/build/Release-iphoneos"'
          end
        end
      end
      aggregate_target.user_project.save
    end
  end
end
